EvidencijaAutomobila/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EvidencijaAutomobila.Models
{
    public class Car
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "This field is required!")]
        [StringLength(50, MinimumLength =2)]
        public string Manufacturer { get; set; }

        [Required(ErrorMessage ="This field is required!")]
        [StringLength(50, MinimumLength = 2,ErrorMessage ="Must be longer then 2 and les then 50 characters")]
        public string Model { get; set; }

        [Required(ErrorMessage = "This field is required!")]
        [StringLength(50, MinimumLength = 2)]
        public string Year { get; set; }

        [Required(ErrorMessage = "This field is required!")]
        [StringLength(4, MinimumLength = 2,ErrorMessage = "Must be longer then 2 and less then 4 characters")]
        public string Volume { get; set; }

        public Engine Engine { get; set; }
        
    }
}

EvidencijaAutomobila/Models/Engine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EvidencijaAutomobila.Models
{
    public class Engine
    {
        public int Id { get; set; }

       // [Display( Name ="Engine name")]
       // [Required(ErrorMessage = "This field is required!")]
       // [StringLength(50, MinimumLength = 2)]
        public string EngineName { get; set; }
    }
}

EvidencijaAutomobila/Controllers/CarController.cs
using EvidencijaAutomobila.Models;
using EvidencijaAutomobila.Repository;
using EvidencijaAutomobila.Repository.Interfaces;
using EvidencijaAutomobila.ViewModel;
using System.Linq;
using System.Web.Mvc;

namespace EvidencijaAutomobila.Controllers
{
    public class CarController : Controller
    {
        ICarRepository CarRepository = new CarRepository();
        IEngineRepository EngineRepository = new EngineRepository();

        // GET: Car
        public ActionResult Index()
        {
            return View(CarRepository.GetAll().ToList());
        }

        public ActionResult Create()
        {
            CarEngineViewModel cewm = new CarEngineViewModel();
            cewm.Car = null;
            cewm.Engines = EngineRepository.GetAll();

            return View(cewm);

        }
        [HttpPost]
        public ActionResult Create(Car car)
        {
            if (ModelState.IsValid)
            {
                              
                CarRepository.Create(car);
                return RedirectToAction("Index");
            }
            CarEngineViewModel cevm = new CarEngineViewModel();
            cevm.Car = car;
            cevm.Engines = EngineRepository.GetAll();
            return View(cevm);

        }

        public ActionResult Update(int id)
        {
            CarEngineViewModel vm = new CarEngineViewModel();
            Car c = CarRepository.GetById(id);

            vm.Car = c;
            vm.Engines = EngineRepository.GetAll();
            vm.selected = c.Engine.Id;
            return View(vm);
        }

        [HttpPost]
        public ActionResult Update(CarEngineViewModel c)
        {
            if (ModelState.IsValid)
            {
                CarRepository.Update(c.Car);
                return RedirectToAction("Index");
            }
            else
            {
                c.Engines = EngineRepository.GetAll();
                return View(c);
            }

        }

        public ActionResult Delete(int id)
        {
            CarRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

EvidencijaAutomobila/Controllers/EngineController.cs
using EvidencijaAutomobila.Models;
using EvidencijaAutomobila.Repository;
using EvidencijaAutomobila.Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EvidencijaAutomobila.Controllers
{
    public class EngineController : Controller
    {
        IEngineRepository EngineRepository = new EngineRepository();

        // GET: Engine
        public ActionResult Index()
        {
            return View(EngineRepository.GetAll());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Engine en)
        {
            if (ModelState.IsValid)
            {
                
                EngineRepository.Create(en);
                return RedirectToAction("Index");
            }
            else
            {
                return View(en);
            }
            
        }

        public ActionResult Delete(int id)
        {
            EngineRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

EvidencijaAutomobila/Views/Car/Create.cshtml
@using EvidencijaAutomobila.ViewModel

@{
    ViewBag.Title = "Create";
}
@model CarEngineViewModel

<h2>Add new car</h2>

@using (Html.BeginForm("Create", "Car", FormMethod.Post,new { onsubmit = "return validateForm(this)" }))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Car.Model)
        @Html.TextBoxFor(m => m.Car.Model, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Car.Model)
        
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Car.Manufacturer)
        @Html.TextBoxFor(m => m.Car.Manufacturer, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Car.Manufacturer)
        
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Car.Volume)
        @Html.TextBoxFor(m => m.Car.Volume, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Car.Volume)
        
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Car.Year)
        @Html.TextBoxFor(m => m.Car.Year, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Car.Year)
        
    </div>
    <div class="form-group">
        @Html.DropDownListFor(m => m.Car.Engine.Id, new SelectList(Model.Engines, "Id", "EngineName"),"Select engine")
        
    </div>

    <div class="form-group">
        <input class="btn btn-default" type="submit" />
    </div>
}

EvidencijaAutomobila/Views/Car/Index.cshtml
@using EvidencijaAutomobila.Models
@{
    ViewBag.Title = "Index";
}
@model IEnumerable<Car>
<h2>Home Page</h2>
<table class="table-striped table-bordered table-hover">
    <tr>
        <th>
            Model
        </th>
        <th>
            Manufacturer
        </th>
        <th>
            Volume
        </th>
        <th>
            Year
        </th>
        <th colspan="3">
            Engine
        </th>
    </tr>
    @foreach (Car cr in Model)
    {
        <tr>
            <td>@cr.Model</td>
            <td>@cr.Manufacturer</td>
            <td>@cr.Volume</td>
            <td>@cr.Year</td>
            <td>@cr.Engine.EngineName</td>
            <td>
                @Html.ActionLink("Edit", "Update", new { id = cr.Id })
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = cr.Id })
            </td>
        </tr>
    }
</table>
 <br/>
<a href="@Url.Action("Create")" class="btn btn-default "> Add new car </a>
<a href="@Url.Action("Create","Engine")" class="btn btn-default "> Add new engine </a>

EvidencijaAutomobila/Views/Car/Update.cshtml
@using EvidencijaAutomobila.ViewModel
@{
    ViewBag.Title = "Update";
}
@model CarEngineViewModel

<h2>Update</h2>

@using (Html.BeginForm("Update", "Car", FormMethod.Post, new { onsubmit = "return validateForm(this)" }))
{
    @Html.HiddenFor(m => m.Car.Id)

    <div class="form-group">
        @Html.LabelFor(m => m.Car.Model)
        @Html.TextBoxFor(m => m.Car.Model, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Car.Model)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Car.Manufacturer)
        @Html.TextBoxFor(m => m.Car.Manufacturer, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Car.Manufacturer)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Car.Volume)
        @Html.TextBoxFor(m => m.Car.Volume, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Car.Volume)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Car.Year)
        @Html.TextBoxFor(m => m.Car.Year, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Car.Year)
    </div>
    <div class="form-group">
        @Html.DropDownListFor(m => m.Car.Engine.Id, new SelectList(Model.Engines, "Id", "EngineName"), "Select engine")
        @Html.ValidationMessageFor(m => m.Car.Engine.Id)
    </div>

    <div class="form-group">
        <input class="btn btn-default" type="submit" />
    </div>
}

EvidencijaAutomobila/Views/Engine/Create.cshtml
@using EvidencijaAutomobila.Models
@{
    ViewBag.Title = "Create";
}
@model Engine
<h2>Add new engine</h2>

@using (Html.BeginForm("Create", "Engine", FormMethod.Post, new { onsubmit = "return validateForm(this)" }))
{
    <div class="form-group">
        @Html.LabelFor(m => m.EngineName)
        @Html.TextBoxFor(m => m.EngineName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.EngineName)  
    </div>

    <div class="form-group">
        <input class="btn btn-default" type="submit" />
    </div>
}

EvidencijaAutomobila/Views/Engine/Index.cshtml

@using EvidencijaAutomobila.Models
@{
    ViewBag.Title = "Index";
}
@model IEnumerable<Engine>
<h2>Home Page</h2>
<table class="table-striped table-bordered table-hover">
    <tr>       
        <th colspan="4">
            Engines
        </th>
    </tr>
    @foreach (Engine en in Model)
    {
        <tr>
            <td>@en.Id</td>
            <td>@en.EngineName</td>
                      
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = en.Id })
            </td>
        </tr>
    }
</table>
<br />
<a href="@Url.Action("Create")" class="btn btn-default "> Add new Engine </a>

EvidencijaAutomobila/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Car Registry", "Index", "Car", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Car")</li>
                    <li>@Html.ActionLink("Engines", "Index", "Engine")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/validation.js"></script>
</body>
</html>